void Send_Pulse_through_EN();
void LCD_initialization();
void LCD_Command(unsigned char cmnd);
void LCD_xy_String(char row, char pos, char *str);
void LCD_Clear();
void LCD_Write_Char(unsigned char data);
void LCD_Write_String(char *str);
void setCursor(int row, int col);
void home();
void underscore();
void hideCursor();
void blink();
void display();
void noDisplay();
void scrollDisplayLeft();
void scrollDisplayRight();
void autoscroll();
void noAutoscroll();
void createChar(int num, unsigned int *charArray);